image: Visual Studio 2019

configuration: 
 - Release
 
before_build:
 - nuget restore
 - nuget install NUnit.Console -Version 3.10.0 -OutputDirectory test_setup
 - nuget install OpenCover -Version 4.7.922 -OutputDirectory test_setup
 - nuget install Codecov -Version 1.5.0 -OutputDirectory test_setup

build:
  project: dotnet-graphloom.sln
  verbosity: minimal

test_script:
 - .\test_setup\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:".\test_setup\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe" -targetargs:".\dotnet-graphloom.UnitTest\bin\Release\GraphLoom.UnitTest.dll" -filter:"+[GraphLoom*]* -[GraphLoom.UnitTest*]*" -output:".\dotnet-graphloom_coverage.xml"
 - .\test_setup\Codecov.1.5.0\tools\codecov.exe -f "dotnet-graphloom_coverage.xml"
