//-----------------------------------------------------------------------
// <copyright file="INodeMap.cs" company="github.com/jiefenn8">
//     Copyright (c) 2019 - GraphLoom contributors
//     (github.com/jiefenn8/dotnet-graphloom)
//
//     This software is made available under the terms of Apache License,
//     Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

using GraphLoom.Mapper.Core.InputSource;
using VDS.RDF;

namespace GraphLoom.Mapper.Core.ConfigMaps
{
    /// <summary>
    /// This interface defines the base method that manages the mapping of any
    /// nodes to their graph node term.
    /// </summary>
    public interface INodeMap
    {
        /// <summary>
        /// Generates a node term with this map using the given entity to
        /// retrieve any data needed.
        /// </summary>
        /// <param name="entity">containing any data needed to generate term</param>
        /// <returns>the node term generated by this node map</returns>
        INode GenerateNodeTerm(IEntity entity);
    }
}
