//-----------------------------------------------------------------------
// <copyright file="IPropertyMap.cs" company="github.com/jiefenn8">
//     Copyright (c) 2019 - GraphLoom contributors
//     (github.com/jiefenn8/dotnet-graphloom)
//
//     This software is made available under the terms of Apache License,
//     Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

using System.Collections.Generic;
using GraphLoom.Mapper.Core.InputSource;
using VDS.RDF;

namespace GraphLoom.Mapper.Core.ConfigMaps
{
    /// <summary>
    /// This interface defines the base methods that manages the mapping
    /// of entity base properties to their graph entity terms.
    /// </summary>
    public interface IPropertyMap
    {
        /// <summary>
        /// Generates an entity term with this map using the given entity to
        /// retrieve any data needed.
        /// </summary>
        /// <param name="entity">containing any data needed to generate term</param>
        /// <returns>the URI generated by this property map</returns>
        IUriNode GenerateEntityTerm(IEntity entity);

        /// <summary>
        /// Returns a list of all class associated with the entity.
        /// </summary>
        /// <returns>the list with all class associated to entity as URIs</returns>
        List<IUriNode> ListEntityClasses();
    }
}
