//-----------------------------------------------------------------------
// <copyright file="IRelationMap.cs" company="github.com/jiefenn8">
//     Copyright (c) 2019 - GraphLoom contributors
//     (github.com/jiefenn8/dotnet-graphloom)
//
//     This software is made available under the terms of Apache License,
//     Version 2.0.
// </copyright>
//-----------------------------------------------------------------------

using GraphLoom.Mapper.Core.InputSource;
using VDS.RDF;

namespace GraphLoom.Mapper.Core.ConfigMaps
{
    /// <summary>
    /// This interface defines the base methods that manages the mapping
    /// of relation to their graph relation term.
    /// </summary>
    public interface IRelationMap
    {
        /// <summary>
        /// Generates a relation term with this map using the given entity to
        /// retrieve any data needed.
        /// </summary>
        /// <param name="entity">containing any data needed to generate term</param>
        /// <returns>the URI generated by this relation map</returns>
        IUriNode GenerateRelationTerm(IEntity entity);
    }
}
